version: "3.9"

services:
    redis:
        image: redis
        container_name: redis
    frontend:
        build: 
            context: ./frontend
            args: 
                - backendUrl=http://192.168.1.109:8080
        ports:
            - 5000:5000
        container_name: frontend
    backend:
        build:
            context: ./backend
            args:
                - reqUrl=http://192.168.1.109:5000
                - redisUrl=redis
        ports:
            - 8080:8080
        container_name: backend
