FROM ubuntu:latest
EXPOSE 5000

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs
RUN node -v && npm -v

WORKDIR /usr/src/myapp
COPY ./example-frontend /usr/src/myapp

RUN npm install
RUN npm install -g serve

ARG backendUrl
RUN echo "backendUrl: $backendUrl"
RUN REACT_APP_BACKEND_URL=$backendUrl npm run build 

CMD ["serve", "-s", "-l", "5000", "build"]
