version: "3.9"

services:
    frontend:
        build: 
            context: ./frontend
            args: 
                - backendUrl=http://192.168.1.109:8080
        ports:
            - 5000:5000
    backend:
        build:
            context: ./backend
            args:
                - reqUrl=http://192.168.1.109:5000
        ports:
            - 8080:8080
                
