version: "3.9"

services:
        colory:
                image: teemukoivumaa/colory
                ports:
                        - 8080:3000
                stdin_open: true
        watchtower:
                image: containrrr/watchtower
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ~teemu/.docker/config.json:/config.json
                command: --interval 30
