FROM golang:1.18

EXPOSE 8080
WORKDIR /usr/src/app
COPY ./example-backend /usr/src/app

RUN go build
RUN go test ./...

ARG reqUrl
ENV REQUEST_ORIGIN $reqUrl

RUN echo "Origin $REQUEST_ORIGIN"

CMD ./server
